#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MugenMvvmToolkit.Android.Resource", IsApplication=false)]

namespace MugenMvvmToolkit.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public static int ActionBarTemplate = 2130771977;
			
			// aapt resource value: 0x7f010000
			public static int Bind = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int Bindings = 2130771969;
			
			// aapt resource value: 0x7f010004
			public static int ContentTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public static int DropDownItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010002
			public static int ItemTemplate = 2130771970;
			
			// aapt resource value: 0x7f010005
			public static int MenuTemplate = 2130771973;
			
			// aapt resource value: 0x7f010008
			public static int PlacementTargetPath = 2130771976;
			
			// aapt resource value: 0x7f010007
			public static int PopupMenuEvent = 2130771975;
			
			// aapt resource value: 0x7f010006
			public static int PopupMenuTemplate = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public static int TabContentId = 2130771978;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030002
			public static int AttachedProperties = 2130903042;
			
			// aapt resource value: 0x7f030001
			public static int ListenParentChange = 2130903041;
			
			// aapt resource value: 0x7f030000
			public static int OptionsMenu = 2130903040;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020000
			public static int Empty = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ActionBar = new int[] {
					2130771977,
					2130771978};
			
			// aapt resource value: 0
			public static int ActionBar_ActionBarTemplate = 0;
			
			// aapt resource value: 1
			public static int ActionBar_TabContentId = 1;
			
			public static int[] Binding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public static int Binding_Bind = 0;
			
			// aapt resource value: 1
			public static int Binding_Bindings = 1;
			
			public static int[] Control = new int[] {
					2130771972};
			
			// aapt resource value: 0
			public static int Control_ContentTemplate = 0;
			
			public static int[] ItemsControl = new int[] {
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public static int ItemsControl_DropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public static int ItemsControl_ItemTemplate = 0;
			
			public static int[] Menu = new int[] {
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public static int Menu_MenuTemplate = 0;
			
			// aapt resource value: 3
			public static int Menu_PlacementTargetPath = 3;
			
			// aapt resource value: 2
			public static int Menu_PopupMenuEvent = 2;
			
			// aapt resource value: 1
			public static int Menu_PopupMenuTemplate = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
